name: Deploy Jekyll with GitHub Pages dependencies preinstalled
on:
  # Runs on pushes targeting the default branch
  push:
    branches: 
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x] # 配置所需node版本
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: npm install
      # 步骤执行指令
        run: npm install
      - name: docs
        run: |
          npm run docs:build --if-present
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './docs/dist'
  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
